import { useState, useEffect } from 'react';
import { useLocation } from 'wouter';
import {
  ArrowUpRight,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Compass,
  DollarSign,
  Home,
  Info,
  Luggage,
  MapPin,
  Sparkles,
  TrainFront,
  Wallet,
} from 'lucide-react';
import { Logo } from '@/components/Logo';
import { useTripContext } from '@/context/TripContext';
import { useModifyItinerary } from '@workspace/api-client-react';
import { useToast } from '@/hooks/use-toast';
import type { ChangeMade, TripHealthScore } from '@workspace/api-client-react';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface ModificationHistoryItem {
  request: string;
  reasoning: string;
  changes: ChangeMade[];
  score_before: TripHealthScore | null;
  score_after: TripHealthScore | null;
  timestamp: Date;
}

// ---------------------------------------------------------------------------
// Health Score UI helpers
// ---------------------------------------------------------------------------

const SCORE_COLORS: Record<string, { bar: string; text: string; bg: string; border: string }> = {
  Excellent:       { bar: 'bg-[#6b9c7b]', text: 'text-[#3d6b50]', bg: 'bg-[#e7f0e9]', border: 'border-[#b2d3bc]' },
  Good:            { bar: 'bg-[#bb7a52]', text: 'text-[#8b4f2a]', bg: 'bg-[#f5e9df]', border: 'border-[#d9b49a]' },
  Fair:            { bar: 'bg-[#c4a84c]', text: 'text-[#7a6420]', bg: 'bg-[#f5f0d9]', border: 'border-[#d9cc9a]' },
  'Needs attention': { bar: 'bg-[#b05050]', text: 'text-[#7a2828]', bg: 'bg-[#f5e0e0]', border: 'border-[#d9a4a4]' },
};

const OVERALL_COLORS: Record<string, string> = {
  Excellent: 'text-[#6b9c7b]',
  Good: 'text-[#e8bc5a]',
  Fair: 'text-[#d4a45a]',
  'Needs attention': 'text-[#c07070]',
};

const DIMENSION_LABELS: Record<string, string> = {
  experience_fit: 'Experience Fit',
  transportation_efficiency: 'Transport Efficiency',
  budget_efficiency: 'Budget Efficiency',
  uniqueness: 'Uniqueness',
  pacing: 'Pacing',
};

const DIMENSION_WEIGHTS: Record<string, string> = {
  experience_fit: '35%',
  transportation_efficiency: '13%',
  budget_efficiency: '20%',
  uniqueness: '10%',
  pacing: '22%',
};

type DimensionKey = 'experience_fit' | 'transportation_efficiency' | 'budget_efficiency' | 'uniqueness' | 'pacing';
const DIMENSIONS: DimensionKey[] = [
  'experience_fit',
  'pacing',
  'budget_efficiency',
  'transportation_efficiency',
  'uniqueness',
];

function formatUsd(value: unknown) {
  const amount = Number(value);
  return `$${(Number.isFinite(amount) && amount >= 0 ? Math.round(amount) : 0).toLocaleString()}`;
}

function ScoreBadge({ label }: { label: string }) {
  const c = SCORE_COLORS[label] ?? SCORE_COLORS.Fair;
  return (
    <span className={`rounded-full border px-2.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide ${c.bg} ${c.border} ${c.text}`}>
      {label}
    </span>
  );
}

function ScoreBar({ score, label }: { score: number; label: string }) {
  const c = SCORE_COLORS[label] ?? SCORE_COLORS.Fair;
  return (
    <div className="h-1.5 w-full overflow-hidden rounded-full bg-[#e2ddd2]">
      <div
        className={`h-full rounded-full transition-all duration-500 ${c.bar}`}
        style={{ width: `${score}%` }}
      />
    </div>
  );
}

function ScoreDelta({ before, after }: { before: number; after: number }) {
  const delta = after - before;
  if (Math.abs(delta) < 1) return null;
  return (
    <span className={`ml-1.5 font-mono-custom text-[10px] ${delta > 0 ? 'text-[#6b9c7b]' : 'text-[#b05050]'}`}>
      {delta > 0 ? '+' : ''}{Math.round(delta)}
    </span>
  );
}

function TripHealthScoreCard({ score }: { score: TripHealthScore }) {
  const [expandedDim, setExpandedDim] = useState<DimensionKey | null>(null);
  const overallColor = OVERALL_COLORS[score.overall_label] ?? 'text-[#e8bc5a]';

  return (
    <div className="rounded-2xl border border-[#d7d0c2] bg-[#fbfaf6]" data-testid="health-score-card">
      {/* Header */}
      <div className="flex items-start gap-5 border-b border-[#e2ddd2] p-5 sm:p-6">
        <div className="flex-1">
          <p className="font-mono-custom text-[10px] uppercase tracking-[.18em] text-[#bb7a52]">
            Experience Score
          </p>
          <p className="mt-1.5 text-sm leading-6 text-[#65706d]">
            Computed from destination attributes, pacing, budget fit, and your interests — not generated by the AI.
          </p>
        </div>
        <div className="text-right">
          <p className={`font-display text-5xl leading-none ${overallColor}`} data-testid="health-score-overall">
            {score.overall}
          </p>
          <p className="mt-1 text-xs text-[#65706d]">out of 100</p>
          <div className="mt-2 flex justify-end">
            <ScoreBadge label={score.overall_label} />
          </div>
        </div>
      </div>

      {/* Sub-scores */}
      <div className="divide-y divide-[#e2ddd2]">
        {DIMENSIONS.map((key) => {
          const sub = score[key];
          const isExpanded = expandedDim === key;
          return (
            <div key={key} data-testid={`score-dim-${key}`}>
              <button
                className="flex w-full items-center gap-4 px-5 py-3.5 text-left hover:bg-[#f5f3ed]"
                onClick={() => setExpandedDim(isExpanded ? null : key)}
              >
                <div className="w-32 shrink-0">
                  <p className="text-xs font-semibold text-[#203b47]">{DIMENSION_LABELS[key]}</p>
                  <p className="mt-0.5 font-mono-custom text-[10px] text-[#a0a8a4]">
                    weight {DIMENSION_WEIGHTS[key]}
                  </p>
                </div>
                <div className="flex-1">
                  <ScoreBar score={sub.score} label={sub.label} />
                </div>
                <div className="flex w-24 shrink-0 items-center justify-end gap-2">
                  <span className="font-mono-custom text-sm text-[#203b47]">{sub.score}</span>
                  <ScoreBadge label={sub.label} />
                  <ChevronDown
                    size={14}
                    className={`shrink-0 text-[#a0a8a4] transition ${isExpanded ? 'rotate-180' : ''}`}
                  />
                </div>
              </button>
              {isExpanded && (
                <div className="border-t border-[#e8e5dc] bg-[#f5f3ec] px-5 py-3">
                  <p className="text-xs leading-5 text-[#65706d]">{sub.explanation}</p>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

export default function Trip() {
  const [, setLocation] = useLocation();
  const [tab, setTab] = useState<'overview' | 'days' | 'practical'>('overview');
  const [filter, setFilter] = useState('All days');
  const [checked, setChecked] = useState<string[]>([]);
  const [openDay, setOpenDay] = useState(0);
  const [chatInput, setChatInput] = useState('');
  const [showChat, setShowChat] = useState(false);
  const [modificationHistory, setModificationHistory] = useState<ModificationHistoryItem[]>([]);
  const [showHistory, setShowHistory] = useState(false);

  const { tripId, itinerary, setItinerary } = useTripContext();
  const { toast } = useToast();
  const modifyItinerary = useModifyItinerary();

  useEffect(() => {
    if (!tripId || !itinerary) {
      setLocation('/plan');
    }
  }, [tripId, itinerary]);

  if (!tripId || !itinerary) {
    return null;
  }

  const visibleDays =
    filter === 'All days'
      ? itinerary.daily_itinerary
      : itinerary.daily_itinerary.filter((d) => d.location.includes(filter));

  const toggleCheck = (id: string) => {
    setChecked(checked.includes(id) ? checked.filter((x) => x !== id) : [...checked, id]);
    toast({ title: checked.includes(id) ? 'Removed from list' : 'Added to your ready list' });
  };

  const handleChatSubmit = () => {
    if (!chatInput.trim() || modifyItinerary.isPending) return;
    const requestText = chatInput;
    setChatInput('');

    modifyItinerary.mutate(
      { id: tripId, data: { user_request: requestText } },
      {
        onSuccess: (data) => {
          setItinerary(data.itinerary);
          setModificationHistory((prev) => [
            {
              request: requestText,
              reasoning: data.reasoning,
              changes: data.changes_made,
              score_before: data.score_before ?? null,
              score_after: data.score_after ?? null,
              timestamp: new Date(),
            },
            ...prev,
          ]);
          const scoreDelta =
            data.score_after && data.score_before
              ? Math.round(data.score_after.overall - data.score_before.overall)
              : null;
          toast({
            title: scoreDelta !== null
              ? `Trip updated · Score ${scoreDelta >= 0 ? '+' : ''}${scoreDelta}`
              : 'Trip updated',
            description: data.reasoning.slice(0, 120) + (data.reasoning.length > 120 ? '…' : ''),
          });
        },
        onError: (error) => {
          console.error('Failed to modify itinerary:', error);
          toast({
            title: 'Modification failed',
            description: 'Unable to update your trip. Please try again.',
            variant: 'destructive',
          });
        },
      }
    );
  };

  const suggestionChips = [
    'Make this cheaper',
    'Add more nature',
    'Reduce travel days',
    'Add a food day',
    'Remove a destination',
    'Slow down the trip',
  ];

  const totalNights = itinerary.route.reduce((sum, stop) => sum + stop.nights, 0);
  const baseCount = itinerary.route.length;
  const locationNames = itinerary.route.map((r) => r.location).join(' → ');

  return (
    <div className="page-grain min-h-[100dvh] bg-[#f3f0e8] text-[#203b47]">
      <header className="border-b border-[#d7d0c2] bg-[#f3f0e8]/90">
        <div className="mx-auto flex max-w-[1220px] items-center justify-between px-5 py-5 sm:px-8">
          <Logo />
          <div className="hidden items-center gap-3 sm:flex">
            <span className="h-2 w-2 rounded-full bg-[#6b9c7b]" />
            <span className="text-xs text-[#65706d]">Your trip is saved in this session</span>
          </div>
          <button
            onClick={() => setLocation('/plan')}
            className="rounded-full border border-[#c9c1b2] px-4 py-2 text-xs font-semibold transition hover:border-[#203b47]"
            data-testid="link-new-trip"
          >
            New trip
          </button>
        </div>
      </header>

      <main className="mx-auto max-w-[1220px] px-5 pb-32 sm:px-8">
        {/* Hero */}
        <div className="border-b border-[#d7d0c2] py-12 sm:py-20">
          <div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end">
            <div>
              <p className="font-mono-custom text-[11px] uppercase tracking-[.18em] text-[#bb7a52]">
                Your route, considered
              </p>
              <h1 className="mt-4 font-display text-5xl leading-[.93] tracking-[-.06em] sm:text-8xl">
                {itinerary.trip_strategy}
              </h1>
              <p className="mt-7 flex items-center gap-2 text-sm text-[#65706d]">
                <MapPin size={15} /> {locationNames}
              </p>
            </div>
            <div className="flex flex-col items-end gap-4">
              {/* Compact overall score in hero */}
              {itinerary.health_score && (
                <div className="flex items-center gap-3 rounded-xl border border-[#d7d0c2] bg-[#f5f3ec] px-4 py-2.5">
                  <div>
                    <p className="font-mono-custom text-[10px] uppercase tracking-widest text-[#bb7a52]">
                      Experience Score
                    </p>
                    <div className="mt-0.5 flex items-baseline gap-1.5">
                      <span
                        className={`font-display text-2xl ${OVERALL_COLORS[itinerary.health_score.overall_label] ?? 'text-[#e8bc5a]'}`}
                      >
                        {itinerary.health_score.overall}
                      </span>
                      <span className="text-xs text-[#65706d]">/ 100</span>
                      <ScoreBadge label={itinerary.health_score.overall_label} />
                    </div>
                  </div>
                </div>
              )}
              <div className="max-w-xs text-right text-sm leading-6 text-[#65706d]">
                <p>{itinerary.total_days} days · {itinerary.total_nights} nights · {baseCount} bases</p>
                <p className="mt-1">{itinerary.reasoning}</p>
              </div>
            </div>
          </div>
        </div>

        {/* Tab bar */}
        <div className="sticky top-0 z-20 -mx-5 flex gap-1 overflow-x-auto border-b border-[#d7d0c2] bg-[#f3f0e8]/95 px-5 py-3 backdrop-blur sm:-mx-8 sm:px-8">
          {(['overview', 'days', 'practical'] as const).map((t) => (
            <button
              key={t}
              onClick={() => setTab(t)}
              className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-semibold capitalize ${
                tab === t ? 'bg-[#203b47] text-[#f5f0e6]' : 'text-[#65706d] hover:bg-[#e7e5d9]'
              }`}
              data-testid={`button-trip-${t}`}
            >
              {t === 'days' ? 'Day by day' : t === 'practical' ? 'Practical notes' : 'Overview'}
            </button>
          ))}
        </div>

        {/* Route visualization — shared between overview and days tabs */}
        {(tab === 'overview' || tab === 'days') && (
          <section className="py-12 sm:py-16">
            <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
              <div>
                <p className="font-mono-custom text-[11px] uppercase tracking-[.18em] text-[#bb7a52]">The route</p>
                <h2 className="mt-2 font-display text-4xl tracking-[-.04em]">
                  A little less map, a lot more place.
                </h2>
              </div>
              <div className="flex items-center gap-2 text-xs text-[#65706d]">
                <span>{totalNights} nights</span>
                <span className="h-1 w-1 rounded-full bg-[#bb7a52]" />
                <span>{itinerary.route.filter((r) => r.transport_to_next).length} transfers</span>
              </div>
            </div>
            <div className="mt-10 overflow-x-auto pb-3">
              <div className="flex min-w-[680px] items-center px-4">
                {itinerary.route.map((stop, i) => {
                  const colors = ['bg-[#d5a58f]', 'bg-[#a9c6b4]', 'bg-[#c2b39a]', 'bg-[#c3d1c6]'];
                  return (
                    <div key={i} className="flex items-center">
                      <div className="flex items-center gap-3">
                        <span className={`flex h-12 w-12 items-center justify-center rounded-full ${colors[i % colors.length]} font-mono-custom text-xs`}>
                          {String(i + 1).padStart(2, '0')}
                        </span>
                        <div>
                          <p className="font-bold">{stop.location}</p>
                          <p className="text-xs text-[#65706d]">{stop.nights} nights</p>
                        </div>
                      </div>
                      {stop.transport_to_next && i < itinerary.route.length - 1 && (
                        <div className="mx-6 h-px w-24 route-line" />
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
            {itinerary.route.some((r) => r.transport_to_next) && (
              <div className="mt-2 flex flex-wrap items-center gap-2 rounded-xl bg-[#e7e5d9] px-4 py-3 text-xs text-[#65706d]">
                <TrainFront size={16} />
                {itinerary.route.map(
                  (stop, i) =>
                    stop.transport_to_next && (
                      <div key={i} className="flex items-center gap-2">
                        <span>{stop.location} → {itinerary.route[i + 1]?.location}</span>
                        <span className="font-mono-custom">
                          {stop.duration_hours ? `${stop.duration_hours}h` : stop.transport_to_next}
                        </span>
                        {i < itinerary.route.filter((r) => r.transport_to_next).length - 1 && (
                          <span className="mx-2 h-3 w-px bg-[#b9b7aa]" />
                        )}
                      </div>
                    )
                )}
              </div>
            )}
          </section>
        )}

        {/* ── OVERVIEW TAB ──────────────────────────────────────────────── */}
        {tab === 'overview' && (
          <>
            {/* Destinations + budget */}
            <section className="grid gap-4 border-t border-[#d7d0c2] py-12 sm:grid-cols-3 sm:py-16">
              <div className="sm:col-span-2">
                <p className="font-mono-custom text-[11px] uppercase tracking-[.18em] text-[#bb7a52]">
                  Your destinations
                </p>
                <div className="mt-7 grid gap-3 sm:grid-cols-3">
                  {itinerary.destinations.slice(0, 3).map((d, i) => {
                    const colors = ['bg-[#a9c6b4]', 'bg-[#c2b39a]', 'bg-[#d5a58f]'];
                    return (
                      <div className={`rounded-2xl ${colors[i]} p-5`} key={d.name} data-testid={`card-trip-destination-${i}`}>
                        <div className="flex justify-between">
                          <span className="font-mono-custom text-[10px]">0{i + 1}</span>
                          <ArrowUpRight size={16} />
                        </div>
                        <p className="mt-16 text-xs">Destination</p>
                        <p className="font-display text-2xl">{d.name}</p>
                        <p className="mt-3 text-xs leading-5 opacity-70">{d.reasoning.slice(0, 80)}…</p>
                      </div>
                    );
                  })}
                </div>
              </div>
              <div className="rounded-2xl bg-[#203b47] p-6 text-[#f5f0e6] sm:p-7">
                <Wallet size={19} className="text-[#e8bc5a]" />
                <p className="mt-10 text-xs text-[#aebeb5]">Estimated on-the-ground</p>
                <p className="mt-2 font-display text-4xl">{formatUsd(itinerary.budget_summary.total_estimated)}</p>
                <div className="mt-7 border-t border-white/15 pt-4 text-xs text-[#c0cec7]">
                  {itinerary.budget_breakdown.slice(0, 3).map((item) => (
                    <div key={item.category} className="flex justify-between py-1">
                      <span>{item.category}</span>
                      <span>{formatUsd(item.estimated_amount)}</span>
                    </div>
                  ))}
                </div>
              </div>
            </section>

            {/* ── TRIP HEALTH SCORE ─────────────────────────────────────── */}
            {itinerary.health_score && (
              <section className="border-t border-[#d7d0c2] py-12 sm:py-16">
                <div className="mb-8 flex flex-col justify-between gap-2 sm:flex-row sm:items-end">
                  <div>
                    <p className="font-mono-custom text-[11px] uppercase tracking-[.18em] text-[#bb7a52]">
                      Optimization
                    </p>
                    <h2 className="mt-2 font-display text-4xl tracking-[-.04em]">
                      How well this trip fits you
                    </h2>
                  </div>
                  <p className="max-w-xs text-sm leading-6 text-[#65706d]">
                    Scored against structured destination attributes — not LLM guesses. Expand each dimension to understand the reasoning.
                  </p>
                </div>
                <TripHealthScoreCard score={itinerary.health_score} />
              </section>
            )}

            {/* Checklist */}
            <Checklist checked={checked} toggleCheck={toggleCheck} itinerary={itinerary} />
          </>
        )}

        {/* ── DAYS TAB ─────────────────────────────────────────────────── */}
        {tab === 'days' && (
          <section className="py-12">
            <div className="mb-6 flex items-center gap-2 overflow-x-auto pb-2">
              <button
                onClick={() => setFilter('All days')}
                className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-semibold ${
                  filter === 'All days' ? 'bg-[#203b47] text-[#f5f0e6]' : 'border border-[#d7d0c2] text-[#65706d]'
                }`}
                data-testid="button-filter-all"
              >
                All days
              </button>
              {itinerary.route.map((stop) => (
                <button
                  key={stop.location}
                  onClick={() => setFilter(stop.location)}
                  className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-semibold ${
                    filter === stop.location
                      ? 'bg-[#203b47] text-[#f5f0e6]'
                      : 'border border-[#d7d0c2] text-[#65706d]'
                  }`}
                  data-testid={`button-filter-${stop.location}`}
                >
                  {stop.location}
                </button>
              ))}
            </div>
            <div className="space-y-3">
              {visibleDays.map((day, i) => (
                <div
                  key={day.day}
                  className={`overflow-hidden rounded-2xl border transition ${
                    openDay === i ? 'border-[#9aada3] bg-[#fbfaf6]' : 'border-[#d7d0c2] bg-transparent'
                  }`}
                >
                  <button
                    onClick={() => setOpenDay(openDay === i ? -1 : i)}
                    className="flex w-full items-center gap-4 p-5 text-left"
                    data-testid={`button-day-${day.day}`}
                  >
                    <div className="flex h-14 w-14 shrink-0 flex-col items-center justify-center rounded-xl bg-[#e7e5d9]">
                      <span className="font-mono-custom text-[10px] text-[#bb7a52]">DAY</span>
                      <span className="font-bold">{day.day}</span>
                    </div>
                    <div className="min-w-0 flex-1">
                      <p className="text-xs text-[#65706d]">{day.date}</p>
                      <h3 className="mt-0.5 font-bold">{day.location}</h3>
                    </div>
                    <ChevronRight size={18} className={`transition ${openDay === i ? 'rotate-90' : ''}`} />
                  </button>
                  {openDay === i && (
                    <div className="border-t border-[#e2ddd2] px-5 pb-5 pt-4 sm:pl-[86px]">
                      <div className="space-y-4">
                        {(['morning', 'afternoon', 'evening'] as const).map((period) => (
                          <div key={period}>
                            <p className="text-xs font-semibold capitalize text-[#bb7a52]">{period}</p>
                            <p className="mt-1 text-sm font-semibold">{day[period].activity}</p>
                            <p className="mt-1 text-sm text-[#65706d]">{day[period].description}</p>
                          </div>
                        ))}
                        <div>
                          <p className="text-xs font-semibold text-[#bb7a52]">Food recommendations</p>
                          <ul className="mt-1 list-disc space-y-1 pl-4 text-sm text-[#65706d]">
                            {day.food_recommendations.map((recommendation) => <li key={recommendation}>{recommendation}</li>)}
                          </ul>
                        </div>
                        {day.transportation && (
                          <div>
                            <p className="text-xs font-semibold text-[#bb7a52]">Transport</p>
                            <p className="mt-1 text-sm text-[#65706d]">
                              {day.transportation.mode} · {day.transportation.details} ({day.transportation.duration})
                            </p>
                          </div>
                        )}
                        <div className="flex items-center gap-2 border-t border-[#d7d0c2] pt-3 text-xs text-[#65706d]">
                          <DollarSign size={14} />
                          <span>Estimated daily cost: {formatUsd(day.estimated_daily_cost_usd)}</span>
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </section>
        )}

        {/* ── PRACTICAL TAB ─────────────────────────────────────────────── */}
        {tab === 'practical' && (
          <section className="py-12">
            <div className="mb-8">
              <p className="font-mono-custom text-[11px] uppercase tracking-[.18em] text-[#bb7a52]">Budget breakdown</p>
              <h2 className="mt-2 font-display text-4xl tracking-[-.04em]">Where your money goes</h2>
            </div>
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {itinerary.budget_breakdown.map((item) => (
                <div key={item.category} className="rounded-xl border border-[#d7d0c2] bg-[#fbfaf6] p-5">
                  <p className="text-xs text-[#bb7a52]">{item.category}</p>
                  <p className="mt-2 font-display text-3xl">{formatUsd(item.estimated_amount)}</p>
                  <p className="mt-3 text-xs leading-5 text-[#65706d]">{item.description}</p>
                </div>
              ))}
            </div>
            {itinerary.tradeoffs && itinerary.tradeoffs.length > 0 && (
              <div className="mt-12">
                <p className="font-mono-custom text-[11px] uppercase tracking-[.18em] text-[#bb7a52]">
                  The trade-offs
                </p>
                <h2 className="mt-2 font-display text-4xl tracking-[-.04em]">What we prioritized</h2>
                <div className="mt-6 space-y-3">
                  {itinerary.tradeoffs.map((item, i) => (
                    <div key={i} className="rounded-xl border border-[#d7d0c2] bg-[#fbfaf6] p-5">
                      <p className="text-sm font-semibold">{item.description}</p>
                      <p className="mt-2 text-xs leading-5 text-[#65706d]">Impact: {item.impact}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </section>
        )}
      </main>

      {/* ── REFINE CHAT PANEL ─────────────────────────────────────────────── */}
      <div className="fixed bottom-0 left-0 right-0 z-30 border-t border-[#d7d0c2] bg-[#f3f0e8]/95 backdrop-blur">
        <div className="mx-auto max-w-[1220px] px-5 py-4 sm:px-8">
          {!showChat ? (
            <button
              onClick={() => setShowChat(true)}
              className="flex w-full items-center justify-between rounded-xl border border-[#d7d0c2] bg-[#fbfaf6] px-5 py-3 text-left transition hover:border-[#203b47]"
              data-testid="button-open-chat"
            >
              <div className="flex items-center gap-3">
                <Sparkles size={18} className="text-[#bb7a52]" />
                <span className="text-sm font-semibold">Refine your trip</span>
                {itinerary.health_score && (
                  <span className="hidden text-xs text-[#65706d] sm:block">
                    — score updates instantly when you make changes
                  </span>
                )}
              </div>
              <span className="text-xs text-[#65706d]">Click to adjust</span>
            </button>
          ) : (
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <Sparkles size={18} className="text-[#bb7a52]" />
                  <span className="text-sm font-semibold">Refine your trip</span>
                </div>
                <button
                  onClick={() => setShowChat(false)}
                  className="text-xs text-[#65706d] hover:text-[#203b47]"
                  data-testid="button-close-chat"
                >
                  Close
                </button>
              </div>
              <div className="flex gap-2 overflow-x-auto pb-1">
                {suggestionChips.map((suggestion) => (
                  <button
                    key={suggestion}
                    onClick={() => setChatInput(suggestion)}
                    className="whitespace-nowrap rounded-full border border-[#d7d0c2] bg-[#fbfaf6] px-3 py-1.5 text-xs transition hover:border-[#203b47] hover:bg-[#e7e5d9]"
                    data-testid={`button-suggestion-${suggestion}`}
                  >
                    {suggestion}
                  </button>
                ))}
              </div>
              <div className="flex gap-2">
                <input
                  value={chatInput}
                  onChange={(e) => setChatInput(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && handleChatSubmit()}
                  placeholder="Ask your travel advisor to adjust the trip…"
                  disabled={modifyItinerary.isPending}
                  className="flex-1 rounded-xl border border-[#d7d0c2] bg-[#fbfaf6] px-4 py-2.5 text-sm outline-none transition focus:border-[#203b47] disabled:opacity-50"
                  data-testid="input-chat"
                />
                <button
                  onClick={handleChatSubmit}
                  disabled={!chatInput.trim() || modifyItinerary.isPending}
                  className="rounded-xl bg-[#203b47] px-5 py-2.5 text-sm font-semibold text-[#f5f0e6] transition hover:bg-[#315565] disabled:cursor-not-allowed disabled:opacity-35"
                  data-testid="button-chat-submit"
                >
                  {modifyItinerary.isPending ? 'Updating…' : 'Send'}
                </button>
              </div>

              {/* Modification history */}
              {modificationHistory.length > 0 && (
                <div>
                  <button
                    onClick={() => setShowHistory(!showHistory)}
                    className="flex items-center gap-2 text-xs text-[#65706d] hover:text-[#203b47]"
                    data-testid="button-toggle-history"
                  >
                    <ChevronRight size={14} className={`transition ${showHistory ? 'rotate-90' : ''}`} />
                    Refinement history ({modificationHistory.length})
                  </button>
                  {showHistory && (
                    <div className="mt-3 max-h-72 space-y-2 overflow-y-auto rounded-xl border border-[#d7d0c2] bg-[#fbfaf6] p-3">
                      {modificationHistory.map((item, i) => (
                        <div key={i} className="border-b border-[#e2ddd2] pb-3 last:border-0">
                          <div className="flex items-start justify-between gap-3">
                            <p className="text-xs font-semibold">{item.request}</p>
                            {item.score_before && item.score_after && (
                              <div className="flex shrink-0 items-center gap-1">
                                <span className="font-mono-custom text-[11px] text-[#65706d]">
                                  {item.score_before.overall}
                                </span>
                                <span className="text-[10px] text-[#a0a8a4]">→</span>
                                <span className={`font-mono-custom text-[11px] font-semibold ${
                                  item.score_after.overall >= item.score_before.overall
                                    ? 'text-[#6b9c7b]'
                                    : 'text-[#b05050]'
                                }`}>
                                  {item.score_after.overall}
                                </span>
                                <ScoreDelta
                                  before={item.score_before.overall}
                                  after={item.score_after.overall}
                                />
                              </div>
                            )}
                          </div>
                          <p className="mt-1 text-xs text-[#65706d]">{item.reasoning}</p>
                          {item.changes.length > 0 && (
                            <ul className="mt-2 space-y-0.5">
                              {item.changes.map((change, ci) => (
                                <li key={ci} className="flex items-start gap-2 text-xs text-[#65706d]">
                                  <CheckCircle2 size={12} className="mt-0.5 shrink-0 text-[#6b9c7b]" />
                                  <span>{change.description}</span>
                                </li>
                              ))}
                            </ul>
                          )}
                          {/* Sub-score deltas */}
                          {item.score_before && item.score_after && (
                            <div className="mt-2 flex flex-wrap gap-2">
                              {DIMENSIONS.map((dim) => {
                                const before = item.score_before![dim].score;
                                const after = item.score_after![dim].score;
                                const delta = after - before;
                                if (Math.abs(delta) < 2) return null;
                                return (
                                  <span
                                    key={dim}
                                    className={`rounded-full px-2 py-0.5 text-[10px] ${
                                      delta > 0
                                        ? 'bg-[#e7f0e9] text-[#3d6b50]'
                                        : 'bg-[#f5e0e0] text-[#7a2828]'
                                    }`}
                                  >
                                    {DIMENSION_LABELS[dim]} {delta > 0 ? '+' : ''}{Math.round(delta)}
                                  </span>
                                );
                              })}
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Checklist sub-component
// ---------------------------------------------------------------------------

function Checklist({
  checked,
  toggleCheck,
  itinerary,
}: {
  checked: string[];
  toggleCheck: (id: string) => void;
  itinerary: any;
}) {
  const checklistItems = [
    { id: 'passport', icon: Luggage, label: 'Check passport validity', detail: 'Valid for 6 months after return' },
    { id: 'accommodation', icon: Home, label: 'Book all accommodation', detail: `${itinerary.route.length} places to confirm` },
    { id: 'transport', icon: TrainFront, label: 'Reserve train tickets', detail: 'Book 2–4 weeks ahead for best prices' },
    { id: 'activities', icon: Compass, label: 'Pre-book key experiences', detail: 'Popular spots fill quickly' },
    { id: 'insurance', icon: Info, label: 'Travel insurance', detail: 'Medical + trip cancellation coverage' },
  ];

  return (
    <section className="border-t border-[#d7d0c2] py-12 sm:py-16">
      <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
        <div>
          <p className="font-mono-custom text-[11px] uppercase tracking-[.18em] text-[#bb7a52]">Ready to go</p>
          <h2 className="mt-2 font-display text-4xl tracking-[-.04em]">Your pre-trip checklist</h2>
        </div>
        <p className="text-xs text-[#65706d]">
          {checked.length} of {checklistItems.length} complete
        </p>
      </div>
      <div className="mt-8 space-y-2">
        {checklistItems.map((item) => {
          const Icon = item.icon;
          const isChecked = checked.includes(item.id);
          return (
            <button
              key={item.id}
              onClick={() => toggleCheck(item.id)}
              className={`flex w-full items-center gap-4 rounded-xl border p-4 text-left transition hover:-translate-y-0.5 ${
                isChecked ? 'border-[#6b9c7b] bg-[#e7f0e9]' : 'border-[#d7d0c2] bg-[#fbfaf6]'
              }`}
              data-testid={`button-checklist-${item.id}`}
            >
              <div className={`flex h-5 w-5 items-center justify-center rounded border ${isChecked ? 'border-[#6b9c7b] bg-[#6b9c7b]' : 'border-[#b5bcb6]'}`}>
                {isChecked && <Check size={14} className="text-white" />}
              </div>
              <Icon size={18} className={isChecked ? 'text-[#6b9c7b]' : 'text-[#65706d]'} />
              <div className="flex-1">
                <p className={`text-sm font-semibold ${isChecked ? 'line-through opacity-60' : ''}`}>{item.label}</p>
                <p className="text-xs text-[#65706d]">{item.detail}</p>
              </div>
            </button>
          );
        })}
      </div>
    </section>
  );
}
